apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-model-pipeline
  labels:
    app: cancerdetection
spec:
  resources:
  - name: model-git
    type: git
  - name: model-image
    type: image
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: S2I_SOURCE_NOTEBOOK_LIST
    type: string
    description: name of the deployment to be patched
  - name: BUILDER_IMAGE
    description: The location of s2i base builder image
    type: string
  tasks:
  - name: build-model
    taskRef:
      name: simple-model-s2i
    params:
      - name: TLSVERIFY
        value: "false"
      - name: BUILDER_IMAGE
        value: $(params.BUILDER_IMAGE)
      - name: LOGLEVEL
        value: '1'
      - name : S2I_SOURCE_NOTEBOOK_LIST
        value: $(params.S2I_SOURCE_NOTEBOOK_LIST)
    resources:
      inputs:
      - name: source
        resource: model-git
      outputs:
      - name: image
        resource: model-image
  - name: deploy-model
    taskRef:
      name: update-deployment
    resources:
      inputs:
      - name: image
        resource: model-image
    params:
    - name: deployment
      value: $(params.deployment-name)
    runAfter:
    - build-model
