apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bcd
  namespace: ai-ml-demo
spec:
  params:
    - default: 'quay.io/hanvithag/model-pipeline-s2i:master'
      name: BUILDER_IMAGE
      type: string
    - default: image_processing_model.ipynb
      name: NOTEBOOK_LIST
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/ai-ml-demo/bcd:latest
      name: MODEL_IMAGE
      type: string
  resources:
    - name: bcd-source
      type: git
    - name: bcd-image
      type: image
  tasks:
    - name: build-bcd-image
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: S2I_SOURCE_NOTEBOOK_LIST
          value: $(params.NOTEBOOK_LIST)
      resources:
        inputs:
          - name: source
            resource: bcd-source
        outputs:
          - name: image
            resource: bcd-image
      taskRef:
        kind: Task
        name: simple-model-s2i
    - name: deploy-bcd-kn-service
      params:
        - name: kn-image
          value: 'registry.redhat.io/openshift-serverless-1/client-kn-rhel8:0.17.3'
        - name: ARGS
          value:
            - service
            - create
            - bcd
            - '--force'
            - '--image=$(params.MODEL_IMAGE)'
            - '--scale-min=1'
            - '--cluster-local'
      runAfter:
        - build-bcd-image
      taskRef:
        kind: ClusterTask
        name: kn