apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: model-image
  labels:
    app: cancerdetection
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/bcddemo/bcd:latest