apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bcd-model-image
  labels:
    app: demo
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/demo/bcd